name: test scheduled reminder

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * MON"

env:
  SLACK_CHANNEL_ID: "C06H8K3VBFE"
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATION_BOT_TOKEN }}

jobs:
  support-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

# must check if the file is a valid csv

      - name: test
        run: |
          grep $TODAY support_reminder/calendar.csv

      - name: Get current PSP and SSP
        run: |
          ls -Al
          cd support_reminder
          TODAY=$(date "+%d %h %Y");
          while IFS="," read -r support_week psp ssp
          do
            echo "SUPPORT_WEEK=$support_week" >> $GITHUB_ENV
            echo "PSP=$psp" >> $GITHUB_ENV
            echo "SSP=$ssp" >> $GITHUB_ENV
          done < <(grep $TODAY calendar.csv)

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: ${{ env.SLACK_CHANNEL_ID }}
          # For posting a simple plain text message
          slack-message: "ðŸš‘ Week: ${{ env.SUPPORT_WEEK }}\n PSP: ${{ env.PSP }}\nSSP: ${{ env.SSP }}."
        env:
          SLACK_BOT_TOKEN: ${{ env.SLACK_BOT_TOKEN }}